# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Readmarker < Formula
  desc "Source-agnostic read-cursor ledger for AI agents"
  homepage "https://github.com/arcmanagement/readmarker"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arcmanagement/readmarker/releases/download/v0.1.2/readmarker_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "b8210d2dbb3b9a37700b8101baf5b149a2e4664495fb068ba3892ad1237ef18d"

      define_method(:install) do
        bin.install "readmarker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arcmanagement/readmarker/releases/download/v0.1.2/readmarker_0.1.2_Darwin_arm64.tar.gz"
      sha256 "176ff98c62445dc924e900d4be607bef268b2d677b933d6b0526a6982a8870bf"

      define_method(:install) do
        bin.install "readmarker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcmanagement/readmarker/releases/download/v0.1.2/readmarker_0.1.2_Linux_x86_64.tar.gz"
      sha256 "ec26cde2dc37a78a080d9708c97a652d62cba112f29d6772dce0900326ffe966"
      define_method(:install) do
        bin.install "readmarker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcmanagement/readmarker/releases/download/v0.1.2/readmarker_0.1.2_Linux_arm64.tar.gz"
      sha256 "8457c274522aadcbdb9b7e03cbe986844e2bd4846513f712e3a73b3aa254836f"
      define_method(:install) do
        bin.install "readmarker"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/readmarker --version")
  end
end
